market/apps/order/urls.py
from django.conf.urls import url

from order.views import ConfirmOrder, ShowOrder, Pay

urlpatterns = [
    url(r'^confirm/$', ConfirmOrder.as_view(), name="确认订单"),
    url(r'^show/$', ShowOrder.as_view(), name="确认支付"),
    url(r'^pay/$', Pay.as_view(), name='支付结果'),
]

market/apps/user/urls.py
from django.conf.urls import url

from DB.base_view import BaseVerifyView
from user.views import LoginView, RegisterView, index, MemberView, ForgetPassView, PersonalCenterView, SendMsm, \
    ResetPasswordView, saftystep, ResetPhoneView, AddressView, AddressAddView, delAddress, AddressEditView

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="用户注册"),
    url(r'^login/$', LoginView.as_view(), name="用户登录"),
    url(r'^index/$', index, name="首页"),
    url(r'^member/$', MemberView.as_view(), name="个人中心"),
    url(r'^PersonalCenter/$', PersonalCenterView.as_view(), name="个人资料"),
    url(r'^forgetpassword/$', ForgetPassView.as_view(), name="忘记密码"),
    # url(r'^code/$', user_code, name="验证码"),
    url(r'^SendMsm/$', SendMsm.as_view(), name="验证码"),
    url(r'^resetpassword/$', ResetPasswordView.as_view(), name="重置密码"),
    url(r"^saftystep/$", saftystep, name='安全设置页'),
    url(r"^resetphone/$", ResetPhoneView.as_view(), name='重置手机号码'),
    url(r'^address/$', AddressView.as_view(), name="收货地址首页"),  # 收货地址首页
    url(r'^address/add/$', AddressAddView.as_view(), name="收货地址添加"),  # 收货地址添加
    url(r'^address/edit/(?P<id>\d+)/$', AddressEditView.as_view(), name="收货地址编辑"),  # 收货地址编辑
    url(r'^address/del/$', delAddress, name="收货地址删除"),  # 收货地址删除



]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import IndexView

urlpatterns = [
    # 上传部件自动调用的上传地址,第三方插件
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='用户')),  # 用户模块
    url(r'^goods/', include('goods.urls', namespace='goods')),  # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include("order.urls", namespace="order")),  # 订单模块
    url(r'^$', IndexView.as_view()),
]

market/apps/order/models.py
from django.db import models

from DB.base_model import Base_model


class Transport(Base_model):
    """运算方式"""
    name = models.CharField(max_length=50, verbose_name="运输方式")
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='运费')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "运输方式管理"
        verbose_name_plural = verbose_name


class Order(Base_model):
    """订单基本信息表"""
    order_status_choices = (
        (0, "未支付"),
        (1, "已支付"),
        (2, "已发货"),
        (3, "未评价"),
        (4, "已完成"),
        (5, "退发货"),
        (6, "取消订单"),
    )
    user = models.ForeignKey(to="user.Users", verbose_name="用户")
    order_sn = models.CharField(max_length=64, verbose_name="订单编号")
    goods_total_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="商品总金额")
    transport_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="运费")
    transport = models.CharField(max_length=50, verbose_name="运输方式")
    username = models.CharField(max_length=50, verbose_name="收货人姓名")
    phone = models.CharField(max_length=11, verbose_name="收货人电话号码")
    address = models.CharField(max_length=250, verbose_name="收货人地址")
    order_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="订单总金额")
    order_status = models.SmallIntegerField(choices=order_status_choices, default=0, verbose_name="订单状态")
    payment = models.ForeignKey(to="Payment", null=True, blank=True, verbose_name="支付方式")

    pay_time = models.DateTimeField(verbose_name="支付时间", null=True, blank=True)
    deliver_time = models.DateTimeField(verbose_name="发货时间", null=True, blank=True)
    finish_time = models.DateTimeField(verbose_name="完成时间", null=True, blank=True)

    def __str__(self):
        return self.order_sn

    class Meta:
        verbose_name = "订单管理"
        verbose_name_plural = verbose_name


class OrderGoods(Base_model):
    """订单商品详情表"""
    order = models.ForeignKey(to="Order", verbose_name="订单ID")
    goods_sku = models.ForeignKey(to="goods.GoodsSKU", verbose_name="订单商品ID")
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="商品价格")
    count = models.SmallIntegerField(verbose_name="订单商品数量")

    def __str__(self):
        return "{}:{}".format(self.order.order_sn, self.goods_sku.sku_name)

    class Meta:
        verbose_name = "订单商品管理"
        verbose_name_plural = verbose_name


class Payment(Base_model):
    name = models.CharField(max_length=50, verbose_name="支付方式")
    brief = models.CharField(max_length=200, verbose_name="说明")
    logo = models.ImageField(upload_to="payment/%Y", verbose_name="支付LOGO")
    is_tj = models.BooleanField(default=False, verbose_name="是否推荐")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "支付方式管理"
        verbose_name_plural = verbose_name

market/apps/order/views.py
import os
import random
from datetime import datetime
from time import sleep

from alipay import AliPay
from django.db import transaction
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django_redis import get_redis_connection

from DB.base_view import BaseVerifyView
from cart.helper import get_cart_key, json_msg
from goods.models import GoodsSKU
from market import settings

from order.models import Transport, Order, OrderGoods, Payment

from user.models import Users, SpAddress


class ConfirmOrder(BaseVerifyView):
    """确认订单页面"""

    def get(self, request):
        """
            1. 如果没有收货地址显示添加收货地址
               如果有收货地址, 显示默认收货地址, 如果没有默认显示第一个


            2. 展示商品信息
                a. 获取商品sku_ids
                    如何获取多个参数的值 getlist() get()只能获取一个

                b. 根据商品id获取商品信息 并且 获取购物车redis中的数量


        """
        user_id = request.session.get("ID")
        # >>>> 1. 收货地址处理
        address = SpAddress.objects.filter(user_id=user_id).order_by("-isDefault").first()
        # address = None

        # 处理商品信息
        sku_ids = request.GET.getlist("sku_ids")
        # 准备空列表 装商品
        goods_skus = []
        # 准备商品总计
        goods_total_price = 0

        # 准备redis
        r = get_redis_connection()
        # 准备键
        cart_key = get_cart_key(user_id)

        # 遍历
        for sku_id in sku_ids:
            # 商品信息
            try:
                goods_sku = GoodsSKU.objects.get(pk=sku_id)
            except GoodsSKU.DoesNotExist:
                # 商品不存在就回到购物车
                return redirect("cart:购物车展示")

            # 获取对应商品的数量
            try:
                count = r.hget(cart_key, sku_id)
                count = int(count)
            except:
                # 商品不存在就回到购物车
                return redirect("cart:购物车展示")

            # 保存到商品对象上
            goods_sku.count = count

            # 装商品
            goods_skus.append(goods_sku)

            # 统计商品总计
            goods_total_price += goods_sku.price * count

        # 获取运输方式
        transports = Transport.objects.filter(is_delete=False).order_by('price')

        # 渲染数据
        context = {
            'address': address,
            'goods_skus': goods_skus,
            'goods_total_price': goods_total_price,
            'transports': transports,
        }
        return render(request, 'order/tureorder.html', context=context)

    @transaction.atomic
    def post(self, request):
        """
            保存订单数据
            1. 订单基本信息表 和 订单商品表
        """
        # 1. 接收参数
        transport_id = request.POST.get('transport')
        sku_ids = request.POST.getlist('sku_ids')
        address_id = request.POST.get('address')

        # 接收用户的id
        user_id = request.session.get("ID")
        user = Users.objects.get(pk=user_id)

        # 验证数据的合法性
        try:
            transport_id = int(transport_id)
            address_id = int(address_id)
            sku_ids = [int(i) for i in sku_ids]
        except:
            return JsonResponse(json_msg(2, "参数错误"))

        # 验证收货地址和运输方式存在
        try:
            address = SpAddress.objects.get(pk=address_id)
        except SpAddress.DoesNotExist:
            return JsonResponse(json_msg(3, "收货地址不存在!"))

        try:
            transport = Transport.objects.get(pk=transport_id)
        except Transport.DoesNotExist:
            return JsonResponse(json_msg(4, "运输方式不存在!"))

        # 2. 操作数据
        # 创建保存点
        sid = transaction.savepoint()
        # >>>1 . 操作订单基本信息表
        order_sn = "{}{}{}".format(datetime.now().strftime("%Y%m%d%H%M%S"), user_id, random.randrange(10000, 99999))
        address_info = "{}{}{}-{}".format(address.hcity, address.hproper, address.harea, address.detail)
        try:
            order = Order.objects.create(
                user=user,
                order_sn=order_sn,
                transport_price=transport.price,
                transport=transport.name,
                username=address.username,
                phone=address.phone,
                address=address_info
            )
        except:
            return JsonResponse(json_msg(8, "创建订单基本数据失败"))

        # >>>2. 操作订单商品表
        # 操作redis
        r = get_redis_connection()
        cart_key = get_cart_key(user_id)

        # 准备个变量保存商品总金额
        goods_total_price = 0
        for sku_id in sku_ids:

            # 获取商品对象
            try:
                goods_sku = GoodsSKU.objects.get(pk=sku_id, is_delete=False, is_on_sale=True)
            except GoodsSKU.DoesNotExist:
                # 回滚数据
                transaction.savepoint_rollback(sid)
                return JsonResponse(json_msg(5, "商品不存在"))

            # 获取购物车中商品的数量
            # redis 基于内存的存储,有可能数据会丢失
            try:
                count = r.hget(cart_key, sku_id)
                count = int(count)
            except:
                transaction.savepoint_rollback(sid)
                return JsonResponse(json_msg(6, "购物车中数量不存在!"))

            # 判断库存是否足够
            if goods_sku.stock < count:
                transaction.savepoint_rollback(sid)
                return JsonResponse(json_msg(7, "库存不足!"))

            # 保存订单商品表
            order_goods = OrderGoods.objects.create(
                order=order,
                goods_sku=goods_sku,
                price=goods_sku.price,
                count=count
            )

            # 添加商品总金额
            goods_total_price += goods_sku.price * count

            # 扣除库存, 销量增加
            # rs = GoodsSKU.objects.filter(pk=sku_id,stock=goods_sku.stock).update(stock=goods_sku.stock-count)
            goods_sku.stock -= count
            goods_sku.sale_num += count
            goods_sku.save()

        # 3. 反过头来操作订单基本信息表 商品总金额 和 订单总金额
        # 订单总金额
        try:
            order_price = goods_total_price + transport.price
            order.goods_total_price = goods_total_price
            order.order_price = order_price
            order.save()
        except:
            # 回滚
            transaction.savepoint_rollback(sid)
            return JsonResponse(json_msg(9, "更新订单失败"))
        # transaction.savepoint_rollback(sid)
        # 4. 清空redis中的购物车数据(对应sku_id)
        r.hdel(cart_key, *sku_ids)

        # 下单成功, 提交事务
        transaction.savepoint_commit(sid)

        # 3. 合成响应
        return JsonResponse(json_msg(0, "创建订单成功!", data=order_sn))


class ShowOrder(BaseVerifyView):
    """确认支付页面"""

    def get(self, request):
        # 接收参数
        order_sn = request.GET.get('order_sn')
        user_id = request.session.get("ID")
        # 操作数据
        # 获取订单信息
        order = Order.objects.get(order_sn=order_sn, user_id=user_id)

        # 获取支付方式
        payments = Payment.objects.filter(is_delete=False).order_by('id')

        # 渲染数据
        context = {
            'order': order,
            'payments': payments,
        }

        return render(request, 'order/order.html', context=context)

    def post(self, request):

        # 参数接收
        payment = request.POST.get('payment')
        order_sn = request.POST.get('order_sn')
        user_id = request.session.get('ID')

        # 判断参数合法性
        try:
            payment = int(payment)
        except:
            return JsonResponse(json_msg(1, "参数错误"))

        # 支付方式存在
        try:
            payment = Payment.objects.get(pk=payment)
        except Payment.DoesNotExist:
            return JsonResponse(json_msg(2, "支付方式不存在"))

        # 判断该订单是否是自己的, 并且是一个未支付的订单
        try:
            order = Order.objects.get(user_id=user_id, order_sn=order_sn, order_status=0)
        except Order.DoesNotExist:
            return JsonResponse(json_msg(3, "订单不满足要求"))

        # 判断 用户是否需要使用支付宝支付
        if payment.name == "支付宝":
            # 构造支付请求
            app_private_key_string = open(os.path.join(settings.BASE_DIR, "alipay/user_private_key.txt")).read()
            alipay_public_key_string = open(os.path.join(settings.BASE_DIR, 'alipay/alipay_public_key.txt')).read()

            # 初始化对象
            alipay = AliPay(
                appid="2016092400582019",
                app_notify_url=None,  # 默认回调url
                app_private_key_string=app_private_key_string,
                # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
                alipay_public_key_string=alipay_public_key_string,
                sign_type="RSA2",  # RSA 或者 RSA2
                debug=True  # 默认False
            )

            # 构造请求地址
            order_string = alipay.api_alipay_trade_wap_pay(
                out_trade_no=order.order_sn,  # 订单编号
                total_amount=str(order.order_price),  # 订单金额
                subject="张爸爸超市订单支付",  # 订单描述
                return_url="http://127.0.0.1:8008/order/pay/",  # 同步通知地址
                notify_url=None  # 异步通知地址 重要
            )

            # 拼接地址
            url = "https://openapi.alipaydev.com/gateway.do?" + order_string

            # 通过json返回请求地址
            return JsonResponse(json_msg(0, "创建支付地址成功", data=url))
        else:
            return JsonResponse(json_msg(4, "该支付方式暂不支支持"))


class Pay(BaseVerifyView):
    """展示支付结果"""

    def get(self, request):

        # 查询订单是否交易成功
        # 构造支付请求
        app_private_key_string = open(os.path.join(settings.BASE_DIR, "alipay/user_private_key.txt")).read()
        alipay_public_key_string = open(os.path.join(settings.BASE_DIR, 'alipay/alipay_public_key.txt')).read()

        # 初始化对象
        alipay = AliPay(
            appid="2016092400582019",
            app_notify_url=None,  # 默认回调url
            app_private_key_string=app_private_key_string,
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_string=alipay_public_key_string,
            sign_type="RSA2",  # RSA 或者 RSA2
            debug=True  # 默认False
        )

        # 获取订单编号
        order_sn = request.GET.get('out_trade_no')
        total_amount = request.GET.get('total_amount')

        # check order status
        paid = False
        for i in range(10):
            # 根据订单编号查询

market/templates/order/order.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}

{% block title %}
    确认支付
{% endblock %}

{% block head_js %}
    <script src="{% static 'js/date.js' %}"></script>
    <script src="{% static 'js/iscroll.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#beginTime').date();
            $('#endTime').date({theme: "datetime"});
        });
    </script>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认支付</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <h5 class="order-tit">收货人信息</h5>
    <div class="order-name">
        <p class="order-tele">{{ order.username }}&nbsp;&nbsp;&nbsp;{{ order.phone }}</p>
        <p class="order-add">{{ order.address }}</p>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <h5 class="order-tit">确认订单信息</h5>
    <ul class="shopcart-list" style="padding-bottom: 0; margin-top: 0;">
        {% for order_goods in order.ordergoods_set.all %}
            <li>
                <img src="{{ MEDIA_URL }}{{ order_goods.goods_sku.logo }}" class="shop-pic"/>
                <div class="order-mid">
                    <div class="tit">{{ order_goods.goods_sku.goods_spu.spu_name }}&nbsp;&nbsp;{{ order_goods.goods_sku.sku_name }}</div>
                    <div class="order-price">￥{{ order_goods.price }} <i>X{{ order_goods.count }}</i></div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <ul class="order-infor">
        <li class="order-infor-first">
            <span>商品总计：</span>
            <i>￥{{ order.goods_total_price }}</i>
        </li>
        <li class="order-infor-first">
            <span>运费：</span>
            <i>{{ order.transport }}-￥{{ order.transport_price }}</i>
        </li>
        {#        <li class="order-infor-first">#}
        {#            <a href="integral.html">积分抵费></a>#}
        {#        </li>#}
        {#        <li class="order-infor-first">#}
        {#            <a href="yhq.html">选择优惠券></a>#}
        {#        </li>#}
    </ul>
    <div style="background: #eee; height: 10px;"></div>
    <textarea placeholder="备注说明" class="bz-infor"></textarea>
    <div style="background: #eee; height: 10px;"></div>




    <ul class="pay-style">
        <form method="post" action="">
            {% csrf_token %}
            <input type="hidden" name="order_sn" value="{{ order.order_sn }}">
            {% for payment in payments %}
                <li>
                    <img src="{{ MEDIA_URL }}{{ payment.logo }}" width="50"/>
                    <span>
                        <p>{{payment.name}}</p>
                        <p class="descript">{{payment.brief}}</p>
                    </span>
                    <label class="am-radio-inline">
                        <input type="radio" {% if payment.is_tj %}checked="checked"{% endif %} name="payment" value="{{payment.pk}}" data-am-ucheck>
                    </label>
                </li>
            {% endfor %}
        </form>

    </ul>

     <div class="shop-fix">
        <div class="order-text">
            应付总额：<span>￥{{ order.order_price }}</span>
        </div>
        <a href="javascript:;" class="js-btn">确认支付</a>
    </div>

    <div style="height: 55px;"></div>
{% endblock %}

<!--底部-->
{% block footer %}
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="index.html" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="shopcart.html" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="member.html" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}


{% block footer_js %}
    <script>
        $(function () {
            //点击按钮确认支付
            $(".js-btn").on('click',function () {
                //准备数据
                var data = $("form").serialize();
                //发起请求
                $.ajax({
                    type:"post",
                    url:"{% url 'order:确认支付' %}",
                    data:data,
                    dataType:"json",
                    success:function (data) {
                        {#console.debug(data);#}
                        if (data.code == 0){
                            //成功跳转到支付地址
                            location.href = data.data;
                        }else {
                            alert(data.errmsg);
                        }
                    }
                });
            })
        })
    </script>
{% endblock %}

market/templates/order/pay.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}

{% block title %}
    支付结果
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">完成支付</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <ul class="order-detail">
        <li><span>订单编号：</span>{{ order_sn }}</li>
        <li><span>订单总价：</span>￥{{ total_amount }}</li>
    </ul>
    <input type="button" class="login-btn" value="{{ result }}">
{##}
{#        <a href="{% url 'goods:首页' %}"  type="button"  class="curr">#}
{#            <span class="am-icon-home"></span>#}
{#            <span class="am-navbar-label">返回首页</span>#}
{#        </a>#}

{% endblock %}


{% block footer %}
    {% include 'basetem/footer.html' %}
{% endblock %}

market/templates/order/tureorder.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}
{% block title %}
    确认订单
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认订单</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {% if address is None %}
            <div class="add-address">
                <a href="{% url '用户:收货地址添加' %}">+新建收货地址</a>
                <i class="am-icon-angle-right"></i>
            </div>
        {% else %}
            <h5 class="order-tit">收货人信息</h5>
            <div class="order-name">
                <a href="{% url '用户:收货地址首页' %}">
                    <p class="order-tele">{{ address.username }}&nbsp;&nbsp;&nbsp;{{ address.phone }}</p>
                    <p class="order-add">
                        {{ address.hcity }}{{ address.hproper }}{{ address.harea }} {{ address.brief }}</p>
                </a>
                <i class="am-icon-angle-right"></i>
            </div>
            <input type="hidden" name="address" value="{{ address.pk }}"/>
        {% endif %}
        <div style="background: #eee; height: 10px;"></div>
        <ul class="shopcart-list" style="padding-bottom: 0;">
            {% for goods_sku in goods_skus %}
                <li>
                    <img src="{{ MEDIA_URL }}{{ goods_sku.logo }}" class="shop-pic"/>
                    <div class="order-mid">
                        <div class="tit">{{ goods_sku.goods_spu.spu_name }} {{ goods_sku.sku_name }}</div>
                        <div class="order-price">￥{{ goods_sku.price }} <i>X{{ goods_sku.count }}</i></div>
                    </div>
                    <input type="hidden" name="sku_ids" value="{{ goods_sku.pk }}">
                </li>
            {% endfor %}
        </ul>
        <ul class="order-infor">
            <li class="order-infor-first">
                <span>商品总计：</span>
                <i>￥<span id="goods_price">{{ goods_total_price }}</span></i>
            </li>
            <li class="order-infor-first">
                <span>运输方式：</span>
                <i>
                    <select name="transport" id="transport">
                        {% for transport in transports %}
                            <option value="{{ transport.pk }}" price="{{ transport.price }}">
                                {{ transport.name }}-¥{{ transport.price }}
                            </option>
                        {% endfor %}
                    </select>
                </i>
            </li>
            {#        <li class="order-infor-first">#}
            {#            <a href="">积分抵费></a>#}
            {#        </li>#}
            {#        <li class="order-infor-first">#}
            {#            <a href="">选择优惠券></a>#}
            {#        </li>#}
        </ul>
        <div style="background: #eee; height: 10px;"></div>
        <textarea placeholder="备注说明" class="bz-infor"></textarea>
        <div style="background: #eee; height: 10px;"></div>
        <div style="height: 55px;"></div>
        <div class="shop-fix">
            <div class="order-text">
                应付总额：<span>￥<i id="total_price">0.00</i></span>
            </div>
            <a href="javascript:;" class="js-btn">提交订单</a>
        </div>
    </form>
{% endblock %}



{% block footer %}
    {% include 'basetem/footer.html' %}
{% endblock %}


{% block footer_js %}
    <script>
        $(function () {
            //计算应付总金额
            function totalPrice() {
                //获取商品的总金额
                var goods_price = $("#goods_price").text();
                //获取运费
                var transport_price = $("#transport").find(":selected").attr('price');
                //订单总金额
                var total_price = Number(goods_price) + Number(transport_price);
                {#console.debug(total_price);#}
                $("#total_price").text(total_price.toFixed(2));
            }

            //调用
            totalPrice();

            //绑定修改事件
            $("#transport").on("change", function () {
                //重新计算价格
                totalPrice();
            });


            //绑定点击事件,提交订单数据
            $(".js-btn").on("click", function () {
                //准备数据
                var data = $("form").serialize();
                //发送ajax
                $.ajax({
                    type:"post",
                    url:"{% url 'order:确认订单' %}",
                    data:data,
                    dataType:"json",
                    success:function (data) {
                        if(data.code == 0){
                            //跳转到确认支付页面
                            location.href = "{% url 'order:确认支付' %}?order_sn="+data.data;
                        } else {
                            alert(data.errmsg);
                        }
                    }
                });
            })
        });
    </script>
{% endblock %}